name: TRate
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8081:8081"
    volumes:
      - ./containers/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - auth
      - process-translation

  auth:
    build: ./containers/auth
    container_name: auth
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    healthcheck:
      test: "curl -f http://localhost:3000/healthcheck"
      interval: 20s
      timeout: 45s
      retries: 2
    environment:
      - DATABASE_URL=postgresql://${POSTGRESDB_USER}:${POSTGRESDB_PASSWORD}@postgresdb:5432/postgresdb
  
  postgresdb:
    build: ./containers/postgresdb
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgresdb-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRES_DB=postgresdb
    
  app:
    build: ./containers/app
    container_name: app
    ports:
      - "5000:5000"

  open-ai-translation:
    build: ./containers/open-ai-translation
    container_name: open-ai-translation
    ports:
      - "5001:5001"
    environment:
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
    depends_on:
      - rabbitmq

  process-translation:
    build: ./containers/process-translation
    container_name: process-translation
    ports:
      - "5002:5002"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq/
      - rabbitmq-log-volume:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3



volumes:
  postgresdb-volume:
    name: postgresdb-volume
  rabbitmq-data-volume:
    name: rabbitmq-data-volume
  rabbitmq-log-volume:
    name: rabbitmq-log-volume
  autoheal-volume:
    name: autoheal-volume